### ISSUE TITLE
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

### ISSUE THREAD

**Issue by harishsupraja** [MediaBrowser/MediaBrowser.Kodi#115]
Getting the Error and No Video is working.

Movierulz is the video addon

00:19:19 T:32  NOTICE: -->Python Interpreter Initialized<--
00:19:19 T:32  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:20 T:32  NOTICE: http://embedscr.to/?p=781
00:19:20 T:32  NOTICE: https://openload.co/embed/3xslg0ncrwi/
00:19:20 T:32  NOTICE: inresolver=https://openload.co/embed/3xslg0ncrwi/
00:19:20 T:32  NOTICE: {url: |https://openload.co/embed/3xslg0ncrwi/| host: || media_id: ||}
00:19:21 T:32   ERROR: URLResolver: AttributeError Error - From: openload Link: https://openload.co/embed/3xslg0ncrwi/: 'NoneType' object has no attribute 'group'
00:19:21 T:32  NOTICE: inresolver=https://openload.co/embed/3xslg0ncrwi/
00:19:21 T:32   ERROR: URLResolver: AttributeError Error - From: openload Link: https://openload.co/embed/3xslg0ncrwi/: 'NoneType' object has no attribute 'group'
00:19:21 T:32 WARNING: URLResolver: no playable streams found
00:19:21 T:32  NOTICE: inresolver=http://embedscr.to/?p=781
00:19:21 T:32   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:26 T:11324  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:26 T:11324  NOTICE: -->Python Interpreter Initialized<--
00:19:26 T:11324  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:27 T:11324  NOTICE: http://embedsr.to/?p=6991
00:19:27 T:11324 WARNING: URLResolver: no playable streams found
00:19:27 T:11324  NOTICE: inresolver=http://embedsr.to/?p=6991
00:19:27 T:11324   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:28 T:12036  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:28 T:12036  NOTICE: -->Python Interpreter Initialized<--
00:19:29 T:12036  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:29 T:12036  NOTICE: http://embedsr.to/?p=6989
00:19:29 T:12036  NOTICE: http://hqq.tv/player/embed_player.php?vid=238263264222277223255243209277242213194271217261258&#038;autoplay=no
00:19:31 T:12036 WARNING: URLResolver: no playable streams found
00:19:31 T:12036  NOTICE: inresolver=http://embedsr.to/?p=6989
00:19:31 T:12036   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:32 T:8500  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:32 T:8500  NOTICE: -->Python Interpreter Initialized<--
00:19:32 T:8500  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:33 T:8500  NOTICE: http://embedsr.to/?p=6993
00:19:33 T:8500 WARNING: URLResolver: no playable streams found
00:19:33 T:8500  NOTICE: inresolver=http://embedsr.to/?p=6993
00:19:33 T:8500   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:33 T:8316  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:33 T:8316  NOTICE: -->Python Interpreter Initialized<--
00:19:34 T:8316  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:35 T:8316  NOTICE: http://embedsr.to/?p=6995
00:19:35 T:8316 WARNING: URLResolver: no playable streams found
00:19:35 T:8316  NOTICE: inresolver=http://embedsr.to/?p=6995
00:19:35 T:8316   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:35 T:2488  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:35 T:2488  NOTICE: -->Python Interpreter Initialized<--
00:19:35 T:2488  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:36 T:2488  NOTICE: http://embedsr.to/?p=6997
00:19:36 T:2488 WARNING: URLResolver: no playable streams found
00:19:36 T:2488  NOTICE: inresolver=http://embedsr.to/?p=6997
00:19:36 T:2488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:37 T:11108  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:37 T:11108  NOTICE: -->Python Interpreter Initialized<--
00:19:37 T:11108  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:38 T:11108  NOTICE: http://embedsr.to/?p=6999
00:19:38 T:11108 WARNING: URLResolver: no playable streams found
00:19:38 T:11108  NOTICE: inresolver=http://embedsr.to/?p=6999
00:19:38 T:11108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:38 T:7552  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:38 T:7552  NOTICE: -->Python Interpreter Initialized<--
00:19:39 T:7552  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:39 T:7552  NOTICE: http://embedsr.to/?p=7001
00:19:39 T:7552 WARNING: URLResolver: no playable streams found
00:19:39 T:7552  NOTICE: inresolver=http://embedsr.to/?p=7001
00:19:39 T:7552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:40 T:7300  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:40 T:7300  NOTICE: -->Python Interpreter Initialized<--
00:19:40 T:7300  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:41 T:7300  NOTICE: http://embedsr.to/?p=7003
00:19:41 T:7300 WARNING: URLResolver: no playable streams found
00:19:41 T:7300  NOTICE: inresolver=http://embedsr.to/?p=7003
00:19:41 T:7300   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:42 T:5884  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:42 T:5884  NOTICE: -->Python Interpreter Initialized<--
00:19:42 T:5884  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:43 T:5884  NOTICE: http://embedsr.to/?p=7005
00:19:43 T:5884 WARNING: URLResolver: no playable streams found
00:19:43 T:5884  NOTICE: inresolver=http://embedsr.to/?p=7005
00:19:43 T:5884   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:44 T:10992  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:44 T:10992  NOTICE: -->Python Interpreter Initialized<--
00:19:44 T:10992  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:45 T:10992  NOTICE: http://embedsr.to/?p=7007
00:19:45 T:10992 WARNING: URLResolver: no playable streams found
00:19:45 T:10992  NOTICE: inresolver=http://embedsr.to/?p=7007
00:19:45 T:10992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:47 T:9804  NOTICE: Thread LanguageInvoker start, auto delete: false
00:19:47 T:9804  NOTICE: -->Python Interpreter Initialized<--
00:19:47 T:9804  NOTICE: URLResolver: Initializing URLResolver version: 3.0.19
00:19:48 T:9804  NOTICE: http://embedsr.to/?p=7009
00:19:48 T:9804 WARNING: URLResolver: no playable streams found
00:19:48 T:9804  NOTICE: inresolver=http://embedsr.to/?p=7009
00:19:48 T:9804   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'vidlink' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1705, in <module>
                                                loadVideos(url,name)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1477, in loadVideos
                                                vlink=ParseVideoLink(newlink)
                                              File "C:\Users\Harish\AppData\Roaming\Kodi\addons\plugin.video.movierulz\default.py", line 1457, in ParseVideoLink
                                                return vidlink
                                            UnboundLocalError: local variable 'vidlink' referenced before assignment
                                            -->End of Python script error report<--
00:19:58 T:8012  NOTICE: Thread BackgroundLoader start, auto delete: false
00:19:58 T:12824  NOTICE: Thread JobWorker start, auto delete: true
00:20:07 T:6728  NOTICE: Thread BackgroundLoader start, auto delete: false
00:20:07 T:9836  NOTICE: Thread JobWorker start, auto delete: true
00:20:12 T:4452  NOTICE: Previous line repeats 1 times.
00:20:12 T:4452  NOTICE: Thread BackgroundLoader start, auto delete: false
00:20:25 T:3280  NOTICE: Thread JobWorker start, auto delete: true

**Comment by angelblue05** [comment]
It's not an Emby for Kodi issue.
